import { useState } from 'react';
import type { ComponentSpec } from '../catalog-types';
import { Field, Icon, ImageOrPlaceholder, OrderActions, ProductPreview, SectionHeading, UploadButton, emptyComponent, makeId, quantitySummary, reorder } from './admin-components';
import type { ProductRecord, Settings } from './admin-components';

const componentFields: { key: keyof ComponentSpec; label: string; placeholder: string }[] = [
  { key: 'nameEn', label: '英文名称', placeholder: 'Dinner fork' }, { key: 'nameZh', label: '中文名称', placeholder: '主餐叉' },
  { key: 'material', label: '材质', placeholder: '304 stainless steel' }, { key: 'size', label: '尺寸', placeholder: '210 mm' },
  { key: 'weightG', label: '单件重量 (g)', placeholder: '45' }, { key: 'thicknessMm', label: '厚度 (mm)', placeholder: '3.0' },
  { key: 'quantity', label: '每套数量', placeholder: '6' }, { key: 'unit', label: '单位', placeholder: 'pcs' },
];
export function ProductEditor({ draft, settings, busy, isExisting, dirty, update, onSave, onDelete, onUpload }: {
  draft: ProductRecord; settings: Settings; busy: boolean; isExisting: boolean; dirty: boolean;
  update: <K extends keyof ProductRecord>(key: K, value: ProductRecord[K]) => void;
  onSave: () => void; onDelete: () => void; onUpload: (files: File[], callback: (urls: string[]) => void) => void;
}) {
  const [tab, setTab] = useState<'basic' | 'components' | 'details'>('basic');
  const [previewIndex, setPreviewIndex] = useState(0);
  const images = [draft.image, ...(draft.gallery || [])].filter(Boolean);
  return <div className="adm-edit-and-preview"><section className="adm-editor adm-card"><div className="adm-editor-heading"><div><span className="adm-eyebrow">{isExisting ? 'EDIT PRODUCT' : 'NEW PRODUCT'}</span><h2>{draft.nameZh || '新产品'}</h2><small>{dirty ? '有未保存的修改' : '资料已保存'}</small></div><div className="adm-editor-actions"><button className="adm-icon-button danger" title={isExisting ? '删除产品' : '丢弃草稿'} aria-label={isExisting ? '删除产品' : '丢弃草稿'} disabled={busy} onClick={onDelete}><Icon name="trash" /></button><button className="adm-btn adm-primary" disabled={busy || !dirty} onClick={onSave}><Icon name="save" />保存</button></div></div>
    <div className="adm-tabs" role="tablist">{([{ id: 'basic', label: '基本资料' }, { id: 'components', label: '组件规格' }, { id: 'details', label: '图文详情' }] as const).map(item => <button key={item.id} role="tab" aria-selected={tab === item.id} className={tab === item.id ? 'active' : ''} onClick={() => setTab(item.id)}>{item.label}{item.id === 'components' && <span>{draft.components.length}</span>}</button>)}</div>
    <fieldset className="adm-editor-body" disabled={busy}>
    {tab === 'basic' && <>
      <SectionHeading number="01" title="产品身份" description="SKU 是产品唯一标识，创建保存后不可更改。" />
      <div className="adm-field-grid"><Field label="唯一 SKU" value={draft.sku || ''} onChange={value => update('sku', value)} readOnly={isExisting} hint={isExisting ? '已锁定 · 用于识别与询盘清单' : '可编辑，保存后锁定'} /><Field label="原货号 / 图册编号 *" value={draft.catalogId} onChange={value => update('catalogId', value)} placeholder="可随时更新" /><Field label="英文产品名称 *" value={draft.nameEn} onChange={value => update('nameEn', value)} placeholder="Stainless Steel Cutlery Set" wide /><Field label="中文产品名称 *" value={draft.nameZh} onChange={value => update('nameZh', value)} placeholder="不锈钢餐具套装" wide /><Field label="型号" value={draft.model} onChange={value => update('model', value)} placeholder="可选" /><label className="adm-field"><span>产品分类 *</span><select value={draft.category} onChange={event => update('category', event.target.value)}><option value="">请选择分类</option>{settings.categories.map(item => <option key={item.id} value={item.id}>{item.nameZh} · {item.nameEn}</option>)}</select></label><Field label="图片编号" value={draft.imageId} onChange={value => update('imageId', value)} placeholder="可选 · 内部整理用" /><Field label="展示顺序" value={String(draft.order)} onChange={value => update('order', Number(value) || 0)} type="number" hint="数字越小，越靠前" /></div>
      <SectionHeading number="02" title="产品图片" description="使用清晰完整的产品图片，支持主图与多角度图库。" />
      <div className="adm-main-image-editor"><ImageOrPlaceholder alt={draft.nameZh || draft.nameEn || '未命名产品'} src={draft.image} label="尚未上传主图" /><div><b>产品主图</b><p>图片完整显示，不裁切产品。</p><UploadButton label={draft.image ? '更换主图' : '上传主图'} disabled={busy} onFiles={files => onUpload(files.slice(0, 1), urls => update('image', urls[0]))} />{draft.image && <button className="adm-text-button danger" onClick={() => update('image', '')}>移除主图</button>}</div></div>
      <div className="adm-gallery-heading"><b>产品图库 <span>{(draft.gallery || []).length} 张</span></b><UploadButton label="添加图片" multiple disabled={busy} onFiles={files => onUpload(files, urls => update('gallery', [...(draft.gallery || []), ...urls]))} /></div>
      <div className="adm-gallery-editor">{(draft.gallery || []).map((url, index) => <div key={`${url}-${index}`}><img src={url} alt={`图库 ${index + 1}`} /><div><button className="adm-icon-button" aria-label={`图库 ${index + 1} 前移`} disabled={index === 0} onClick={() => update('gallery', reorder(draft.gallery || [], index, -1))}>←</button><button className="adm-icon-button" aria-label={`图库 ${index + 1} 后移`} disabled={index === (draft.gallery || []).length - 1} onClick={() => update('gallery', reorder(draft.gallery || [], index, 1))}>→</button><button className="adm-icon-button danger" aria-label={`移除图库 ${index + 1}`} onClick={() => { update('gallery', (draft.gallery || []).filter((_, imageIndex) => imageIndex !== index)); setPreviewIndex(0); }}>×</button></div></div>)}{!(draft.gallery || []).length && <p className="adm-subtle">还没有图库图片，可添加细节、侧面或包装照片。</p>}</div>
      <SectionHeading number="03" title="发布状态" description="先确认产品资料，再将产品展示给客户。" />
      <label className="adm-toggle-row"><span><b>资料已确认 · Verified</b><small>已核对图片、名称、规格与组件数量。</small></span><input type="checkbox" checked={draft.verificationStatus === 'Verified'} onChange={event => { update('verificationStatus', event.target.checked ? 'Verified' : 'Needs confirmation'); if (!event.target.checked) update('published', false); }} /></label>
      <label className="adm-toggle-row"><span><b>在公开图册上架</b><small>{draft.published ? '保存后客户可以浏览此产品。' : '作为草稿保留，不展示在公开图册中。'}</small></span><input type="checkbox" checked={draft.published} onChange={event => update('published', event.target.checked)} /></label>
    </>}
    {tab === 'components' && <><SectionHeading number="01" title="套装组件与规格" description="每一行是一种组件；「每套数量」表示该组件实际包含几件。" /><div className="adm-component-summary"><div><strong>{draft.components.length}</strong><span>组件种类</span></div><div><strong>{quantitySummary(draft.components)}</strong><span>每套合计数量 · 按单位统计</span></div></div>
      <div className="adm-repeat-list">{draft.components.map((component, index) => <article className="adm-repeat-card" key={component.id}><div className="adm-repeat-heading"><b><span>{String(index + 1).padStart(2, '0')}</span>{component.nameZh || component.nameEn || '新组件'}</b><OrderActions index={index} length={draft.components.length} onMove={direction => update('components', reorder(draft.components, index, direction))} onDelete={() => update('components', draft.components.filter((_, itemIndex) => itemIndex !== index))} label={`组件 ${index + 1}`} /></div><div className="adm-field-grid">{componentFields.map(field => <Field key={field.key} label={field.label} value={component[field.key]} placeholder={field.placeholder} onChange={value => update('components', draft.components.map((item, itemIndex) => itemIndex === index ? { ...item, [field.key]: value } : item))} />)}</div></article>)}</div>
      <button className="adm-add-row" onClick={() => update('components', [...draft.components, emptyComponent()])}><Icon name="plus" />添加组件</button>
      <SectionHeading number="02" title="自定义产品属性" description="用于补充包装、工艺、使用场景等产品信息。" /><div className="adm-attribute-rows">{(draft.attributes || []).map((attribute, index) => <div key={attribute.id}><Field label="属性名称" value={attribute.label} placeholder="表面处理" onChange={value => update('attributes', (draft.attributes || []).map((item, itemIndex) => itemIndex === index ? { ...item, label: value } : item))} /><Field label="属性内容" value={attribute.value} placeholder="Mirror polish / 镜面抛光" onChange={value => update('attributes', (draft.attributes || []).map((item, itemIndex) => itemIndex === index ? { ...item, value: value } : item))} /><button className="adm-icon-button danger" aria-label={`删除属性 ${index + 1}`} onClick={() => update('attributes', (draft.attributes || []).filter((_, itemIndex) => itemIndex !== index))}><Icon name="trash" /></button></div>)}</div><button className="adm-add-row" onClick={() => update('attributes', [...(draft.attributes || []), { id: makeId('attribute'), label: '', value: '' }])}><Icon name="plus" />添加属性</button></>}
    {tab === 'details' && <><SectionHeading number="01" title="产品简介" description="在规格之外，介绍产品的材质、工艺与使用体验。" /><div className="adm-field-grid"><Field label="英文简介" value={draft.descriptionEn || ''} onChange={value => update('descriptionEn', value)} multiline wide placeholder="Describe the design, craftsmanship and intended use…" /><Field label="中文简介" value={draft.descriptionZh || ''} onChange={value => update('descriptionZh', value)} multiline wide placeholder="介绍产品的设计、工艺与适用场景…" /></div>
      <SectionHeading number="02" title="图文内容块" description="自由组合段落与图片，可调整顺序。" /><div className="adm-repeat-list">{(draft.blocks || []).map((block, index) => <article className="adm-repeat-card" key={block.id}><div className="adm-repeat-heading"><b><span>{String(index + 1).padStart(2, '0')}</span>{block.type === 'text' ? '文字段落' : '详情图片'}</b><OrderActions index={index} length={(draft.blocks || []).length} onMove={direction => update('blocks', reorder(draft.blocks || [], index, direction))} onDelete={() => update('blocks', (draft.blocks || []).filter((_, itemIndex) => itemIndex !== index))} label={`详情块 ${index + 1}`} /></div><Field label={block.type === 'text' ? '段落标题' : '图片说明'} value={block.title} onChange={value => update('blocks', (draft.blocks || []).map((item, itemIndex) => itemIndex === index ? { ...item, title: value } : item))} placeholder="可选标题 / 中英文均可" />{block.type === 'text' ? <Field label="段落内容" value={block.content} multiline onChange={value => update('blocks', (draft.blocks || []).map((item, itemIndex) => itemIndex === index ? { ...item, content: value } : item))} placeholder="输入完整的产品说明…" /> : <div className="adm-detail-image-editor"><ImageOrPlaceholder alt={block.title || '产品详情图片'} src={block.content} label="上传详情图片" /><UploadButton label={block.content ? '更换图片' : '上传图片'} disabled={busy} onFiles={files => onUpload(files.slice(0, 1), urls => update('blocks', (draft.blocks || []).map((item, itemIndex) => itemIndex === index ? { ...item, content: urls[0] } : item)))} /></div>}</article>)}</div><div className="adm-add-block-buttons"><button className="adm-add-row" onClick={() => update('blocks', [...(draft.blocks || []), { id: makeId('block'), type: 'text', title: '', content: '' }])}><Icon name="plus" />添加文字</button><button className="adm-add-row" onClick={() => update('blocks', [...(draft.blocks || []), { id: makeId('block'), type: 'image', title: '', content: '' }])}><Icon name="image" />添加图片</button></div></>}
    </fieldset><div className="adm-editor-footer"><span><i className={dirty ? 'unsaved' : ''} />{dirty ? '修改尚未保存' : '资料已保存'}</span><button className="adm-btn adm-primary" disabled={busy || !dirty} onClick={onSave}>保存产品</button></div>
  </section><aside className="adm-preview-wrap"><div className="adm-preview-label"><span><Icon name="eye" />实时预览</span><small>当前编辑内容</small></div><ProductPreview product={draft} categories={settings.categories} images={images} imageIndex={previewIndex} onImageIndex={setPreviewIndex} accent={settings.accent} /></aside></div>;
}
