import { useState } from 'react';
import type { CSSProperties } from 'react';
import { isGitHubAdmin } from './github-store';
import { Field, Icon, ImageOrPlaceholder, OrderActions, SectionHeading, UploadButton, makeId, reorder } from './admin-components';
import type { Category, Notice, ProductRecord, Settings } from './admin-components';

export function SettingsWorkspace({ section, settings, products, busy, update, notify, onUpload }: { section: 'categories' | 'design'; settings: Settings; products: ProductRecord[]; busy: boolean; update: <K extends keyof Settings>(key: K, value: Settings[K]) => void; notify: (text: string, kind?: Notice['kind']) => void; onUpload: (files: File[], callback: (urls: string[]) => void) => void }) {
  const [activeCategory, setActiveCategory] = useState(settings.categories[0]?.id || '');
  const category = settings.categories.find(item => item.id === activeCategory) || settings.categories[0];
  function addCategory() { const next: Category = { id: makeId('category'), nameEn: '', nameZh: '', image: '', descriptionEn: '', descriptionZh: '' }; update('categories', [...settings.categories, next]); setActiveCategory(next.id); }
  function updateCategory(key: keyof Category, value: string) { update('categories', settings.categories.map(item => item.id === category?.id ? { ...item, [key]: value } : item)); }
  function deleteCategory() {
    if (!category) return;
    const count = products.filter(product => product.category === category.id).length;
    if (count) { notify(`「${category.nameZh || category.nameEn}」仍有 ${count} 个产品（包含草稿）。请先将这些产品迁移至其他分类并保存。`, 'error'); return; }
    if (!window.confirm(`确定删除分类「${category.nameZh || category.nameEn || '未命名分类'}」？该分类未保存的修改也会丢弃，${isGitHubAdmin ? '暂存设置并发布后生效' : '保存设置后生效'}。`)) return;
    const remaining = settings.categories.filter(item => item.id !== category.id); update('categories', remaining); setActiveCategory(remaining[0]?.id || '');
  }
  if (section === 'categories') return <div className="adm-category-workspace"><section className="adm-card"><div className="adm-card-heading"><div><h2>图册分类</h2><p>{settings.categories.length} 个分类 · {isGitHubAdmin ? '修改后请暂存并发布' : '修改后请保存'}</p></div><button className="adm-btn" disabled={busy} onClick={addCategory}><Icon name="plus" />新建</button></div><div className="adm-category-list">{settings.categories.map((item, index) => <button className={item.id === category?.id ? 'selected' : ''} key={item.id} disabled={busy} onClick={() => setActiveCategory(item.id)}><span className="adm-category-order">{String(index + 1).padStart(2, '0')}</span><ImageOrPlaceholder alt={item.nameZh || item.nameEn || '分类封面'} src={item.image} /><span><b>{item.nameZh || '新分类'}</b><small>{item.nameEn || '填写英文名称'}</small><em>{products.filter(product => product.category === item.id).length} 个产品</em></span><span>›</span></button>)}{!settings.categories.length && <div className="adm-empty"><Icon name="layers" /><p>创建第一个产品分类。</p></div>}</div></section>
    {category ? <section className="adm-card"><div className="adm-card-heading"><div><h2>{category.nameZh || '编辑新分类'}</h2><p>编辑分类名称、说明与封面。</p></div><button className="adm-icon-button danger" disabled={busy} aria-label="删除分类" onClick={deleteCategory}><Icon name="trash" /></button></div><fieldset className="adm-category-editor" disabled={busy}><div className="adm-category-cover"><ImageOrPlaceholder alt={category.nameZh || category.nameEn || '分类封面'} src={category.image} label="上传分类封面" /><UploadButton label={category.image ? '更换封面' : '上传封面'} disabled={busy} onFiles={files => onUpload(files.slice(0, 1), urls => updateCategory('image', urls[0]))} />{category.image && <button className="adm-text-button danger" onClick={() => updateCategory('image', '')}>移除封面</button>}</div><div className="adm-field-grid"><Field label="英文分类名称 *" value={category.nameEn} onChange={value => updateCategory('nameEn', value)} /><Field label="中文分类名称 *" value={category.nameZh} onChange={value => updateCategory('nameZh', value)} /><Field label="英文分类介绍" value={category.descriptionEn || ''} onChange={value => updateCategory('descriptionEn', value)} multiline wide /><Field label="中文分类介绍" value={category.descriptionZh || ''} onChange={value => updateCategory('descriptionZh', value)} multiline wide /></div><div className="adm-category-actions"><span>分类排序</span><OrderActions label="分类" index={settings.categories.findIndex(item => item.id === category.id)} length={settings.categories.length} onMove={direction => update('categories', reorder(settings.categories, settings.categories.findIndex(item => item.id === category.id), direction))} /></div><p className="adm-inline-note"><Icon name="info" />删除前需将该分类中的产品迁移至其他分类。修改名称不会影响产品归属。</p></fieldset></section> : <section className="adm-card adm-empty"><Icon name="layers" /><h3>选择一个分类</h3><p>或新建分类，整理你的产品系列。</p></section>}
  </div>;
  return <div className="adm-design-workspace"><section className="adm-card"><div className="adm-card-heading"><div><h2>品牌与页面</h2><p>预览会随输入实时更新。</p></div><Icon name="design" /></div><fieldset className="adm-design-controls" disabled={busy}><SectionHeading number="01" title="品牌文字" /><Field label="品牌名称 *" value={settings.brand} onChange={value => update('brand', value)} /><Field label="首页英文标题 *" value={settings.headlineEn} onChange={value => update('headlineEn', value)} multiline /><Field label="首页中文标题 *" value={settings.headlineZh} onChange={value => update('headlineZh', value)} multiline /><Field label="WhatsApp 联系号码" value={settings.whatsapp} onChange={value => update('whatsapp', value)} placeholder="例如 +86 13800138000" hint="填写带国家区号的号码，用于客户询盘。" /><SectionHeading number="02" title="页面样式" /><div className="adm-color-control"><label>强调色<input aria-label="选择强调色" type="color" value={/^#[0-9a-f]{6}$/i.test(settings.accent) ? settings.accent : '#b56a42'} onChange={event => update('accent', event.target.value)} /></label><Field label="颜色代码" value={settings.accent} onChange={value => update('accent', value)} /></div><div className="adm-palette">{['#b56a42', '#1b5547', '#376d84', '#76614d', '#6b587a', '#292c2b'].map(color => <button type="button" key={color} title={color} aria-label={`强调色 ${color}`} className={settings.accent === color ? 'selected' : ''} style={{ backgroundColor: color }} onClick={() => update('accent', color)} />)}</div><label className="adm-field"><span>桌面端每行产品数量</span><div className="adm-column-options">{[2, 3, 4].map(number => <button type="button" key={number} aria-label={`${number} 列`} className={settings.columns === number ? 'active' : ''} onClick={() => update('columns', number)}><Icon name="grid" />{number} 列</button>)}</div></label><p className="adm-subtle">手机端会自动调整布局，保持产品完整可读。</p></fieldset></section>
    <aside className="adm-design-preview"><div className="adm-preview-label"><span><Icon name="eye" />页面预览</span><small>示意布局 · 实际页面自适应屏幕</small></div><div className="adm-browser-frame" style={{ '--preview-accent': settings.accent } as CSSProperties}><div className="adm-browser-bar"><i /><i /><i /><span>catalogue / preview</span></div><div className="adm-site-preview"><header><b>{settings.brand || 'YOUR BRAND'}</b><span>PRODUCT CATALOGUE</span></header><div className="adm-site-hero"><span>CURATED FOR EVERYDAY LIVING</span><h2>{settings.headlineEn || 'Your catalogue headline'}</h2><p>{settings.headlineZh}</p><button type="button" tabIndex={-1}>Explore collection ↗</button></div><div className="adm-site-categories"><b>All products</b>{settings.categories.map(item => <span key={item.id}>{item.nameEn || 'New collection'}</span>)}</div><div className="adm-site-products" style={{ gridTemplateColumns: `repeat(${settings.columns}, minmax(0, 1fr))` }}>{products.filter(product => product.published).slice(0, 8).map(product => <article key={product.id}><ImageOrPlaceholder alt={product.nameZh || product.nameEn || '未命名产品'} src={product.image} /><small>{product.sku}</small><b>{product.nameEn}</b><span>{product.nameZh}</span></article>)}{!products.some(product => product.published) && [0, 1, 2, 3].map(index => <article key={index}><ImageOrPlaceholder src="" /><small>PRODUCT PREVIEW</small><b>产品名称示意</b><span>上架产品后显示真实内容</span></article>)}</div><footer>{settings.brand}<span>Thoughtfully made. Beautifully presented.</span></footer></div></div></aside>
  </div>;
}
