$ErrorActionPreference = 'Stop'
Write-Host 'Publishing is now available in the online management system:'
Write-Host 'https://qiao13822919184-byte.github.io/yumingxing_catalog/admin/'
Write-Host 'Open the URL above, connect to GitHub, edit and publish your catalogue.'
Write-Host 'Local SQLite data is kept separate and will not overwrite online edits.'
